export const TASKS = [
  {
    id: 1,
    title: "task 1",
    description: "this is description 1",
    status: "todo",
    tag: "frontend",
  },
  {
    id: 2,
    title: "task 2",
    description: "this is description 2",
    status: "inprogress",
    tag: "frontend",
  },
  {
    id: 3,
    title: "task 3",
    description: "this is description 3",
    status: "completed",
    tag: "frontend",
  },
  {
    id: 4,
    title: "task 4",
    description: "this is description 4",
    status: "todo",
    tag: "frontend",
  },
  {
    id: 5,
    title: "task 5",
    description: "this is description 5",
    status: "review",
    tag: "frontend",
  },
  // {
  //   id: 6,
  //   title: "task 6",
  //   description: "this is description 6",
  //   status: "review",
  //   tag: "frontend",
  // },
  // {
  //   id: 7,
  //   title: "task 7",
  //   description: "this is description 7",
  //   status: "todo",
  //   tag: "frontend",
  // },
  // {
  //   id: 8,
  //   title: "task 8",
  //   description: "this is description 8",
  //   status: "review",
  //   tag: "frontend",
  // },
  // {
  //   id: 9,
  //   title: "task 9",
  //   description: "this is description 9",
  //   status: "todo",
  //   tag: "frontend",
  // },
  // {
  //   id: 10,
  //   title: "task 10",
  //   description: "this is description 10",
  //   status: "todo",
  //   tag: "frontend",
  // },
  // {
  //   id: 11,
  //   title: "task 11",
  //   description: "this is description 1",
  //   status: "todo",
  //   tag: "frontend",
  // },
];
